version: '3'

services:
    nginx:
        restart: always
        build: ./nginx
        container_name: nginx
        ports:
            - '80:80'


    jenkins:
        build: ./jenkins
        volumes:
            - /var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        environment:
            DOCKER_SOCKET: /var/run/docker.sock
            DOCKER_GROUP: dockerhost
            JENKINS_USER: jenkins
            JENKINS_URL: "https://jenkins.example.com/"
            DOCKER_HOST: unix:///var/run/docker.sock
        ports:
            - '8080:8080'
            - '50000:50000'        
